version: '3.9'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  
  # Kafka Service (KRaft Mode)
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"  # JMX Monitoring (Optional)
    environment:
      # KRaft Mode Configuration
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # Required for KRaft Mode
      KAFKA_KRAFT_MODE: "true"
      KAFKA_CLUSTER_ID: "kraft-cluster-01"  # Added Cluster ID
      CLUSTER_ID: "kraft-cluster"

      # Replication & Topics Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Monitoring and Healthcheck (Optional)
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network
    restart: always

volumes:
  postgres-data:
  kafka-data:

networks:
  kafka-network:
    driver: bridge

